//
//  SpeechInteractor.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 10/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SpeechBusinessLogic
{
  func doSomething(request: Speech.Something.Request)
}

protocol SpeechDataStore
{
  //var name: String { get set }
}

class SpeechInteractor: SpeechBusinessLogic, SpeechDataStore
{
  var presenter: SpeechPresentationLogic?
  var worker: SpeechWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Speech.Something.Request)
  {
    worker = SpeechWorker()
    worker?.doSomeWork()
    
    let response = Speech.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
