//
//  SpeechPresenter.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 10/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SpeechPresentationLogic
{
  func presentSomething(response: Speech.Something.Response)
}

class SpeechPresenter: SpeechPresentationLogic
{
  weak var viewController: SpeechDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Speech.Something.Response)
  {
    let viewModel = Speech.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
