//
//  DetailWorker.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 09/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker
{
  func doSomeWork()
  {
  }
}
