//
//  ArtistWorker.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 13/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class ArtistWorker
{
    func doSomeWork()
    {
    }
    
    func findTopChart(request: Artist.Artist.Request, callback: @escaping (_ response: Artist.Artist.ResponseArtist) -> ())
    {
        let parameters: Parameters = [
            "method": request.method,
            "country": request.country,
            "api_key": Config().apiKey,
            "format": "json"
        ]
        Alamofire.request(Config().endpoint, method: .get, parameters: parameters, encoding: URLEncoding.default ).responseJSON { data in
            let jsonDecode = try! JSONDecoder().decode(Artist.Artist.ResponseArtist.self, from: data.data!)
            callback(jsonDecode)
        }
    }
}
