//
//  ArtistModels.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 13/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Artist
{
  // MARK: Use cases
  
  enum Artist
  {
    struct Request
    {
        var method: String
        var country: String
    }
    struct Response
    {
    }
    
    struct ResponseArtist: Decodable {
        var topartists: ResponseDataArtist
    }
    struct ViewModel
    {
    }
    
    struct SingleArtist: Decodable {
        var name: String
        var url: String
        var listeners: String
        var country: String?
        var position: Int? = 0
        
        init(name: String, url: String, listeners: String, country: String?, position: Int?) {
            self.name = name
            self.url = url
            self.listeners = listeners
            self.country = country
            self.position = position
        }
    }
    
    struct ResponseDataArtist: Decodable {
        var artist: [SingleArtist]
        
        init(artist: [SingleArtist]) {
            self.artist = artist
        }
        init() {
            self.artist = [SingleArtist]()
        }
    }
    
    
  }
}
