//
//  DashboardPresenter.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 08/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic
{
  func presentSomething(response: Dashboard.Song.ResponseDashboard)
}

class DashboardPresenter: DashboardPresentationLogic
{
  weak var viewController: DashboardDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Dashboard.Song.ResponseDashboard)
  {
    viewController?.displaySomething(viewModel: response)
  }
}
