//
//  DashboardInteractor.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 08/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic
{
  func findTopChart(request: Dashboard.Song.Request)
}

protocol DashboardDataStore
{
  var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore
{
  var presenter: DashboardPresentationLogic?
  var worker: DashboardWorker?
  var name: String = ""
  
  // MARK: Do something
  
  func findTopChart(request: Dashboard.Song.Request)
  {
    worker = DashboardWorker()
    worker?.findTopChart(request: request) { response in
        let response = response
        print("interactoorrr \(response.tracks.track.count)")
        self.presenter?.presentSomething(response: response)
    }
  }
}
