//
//  DashboardWorker.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 08/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
class DashboardWorker
{
    func findTopChart(request: Dashboard.Song.Request, callback: @escaping (_ response: Dashboard.Song.ResponseDashboard) -> ())
  {
    let parameters: Parameters = [
        "method": request.method,
        "api_key": Config().apiKey,
        "format": "json"
    ]
    Alamofire.request(Config().endpoint, method: .get, parameters: parameters, encoding: URLEncoding.default ).responseJSON { data in
        let jsonDecode = try! JSONDecoder().decode(Dashboard.Song.ResponseDashboard.self, from: data.data!)
        callback(jsonDecode)
    }
  }
}
