//
//  DashboardModels.swift
//  CleanSwiftByReni
//
//  Created by Bootcamp on 08/05/19.
//  Copyright (c) 2019 Bootcamp. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Dashboard
{
  // MARK: Use cases
  
  enum Song
  {
    struct Request
    {
        var method: String
        init(method:String) {
            self.method = method
        }
    }
    struct Response
    {
        
    }
    
    struct ResponseDashboard: Decodable {
        var tracks: ResponseDataSong
    }
    
    struct ViewModel
    {
    }
  }
}
